# Generated by Django 3.0.5 on 2020-04-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
