# Generated by Django 3.0.5 on 2020-04-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200425_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
